version: '2'

catalog:
  name: "Splunk Seach Head Cluster (Ephemeral)"
  description: "Deploy a Splunk search head cluster that doesn't use persistent volumes. This stack currently does not support scaling up and down instances. All data will be lost when the container is removed!"
  version: "0.1"
  minimum_rancher_version: v1.6.0
  questions:
    - variable: rancher_stack_name
      label: "Stack Name"
      description: "IMPORTANT: This must be set to the same name as the 'Name' field above, otherwise the cluster will not function. This is a workaround until Rancher implement magic variable names (https://github.com/rancher/rancher/issues/3393)."
      type: "string"
      required: true
    - variable: splunk_accept_license
      label: "Do you accept the Splunk License?"
      description: "The Splunk License can be found here: https://www.splunk.com/en_us/legal/splunk-software-license-agreement.html"
      type: "boolean"
      required: true
    - variable: splunk_web_port
      label: "Splunk Web Port"
      description: "Choose a port for the cluster's load balanced web GUI to be exposed on"
      type: "int"
      required: true
      default: 8000
    - variable: splunk_cluster_label
      label: "Splunk Cluster Label"
      description: "Choose a label for your search head cluster"
      type: "string"
    - variable: splunk_rep_factor
      label: "Splunk Replication Factor"
      description: "The replication factor for the cluster, see http://docs.splunk.com/Documentation/Splunk/6.5.3/DistSearch/SHCdeploymentoverview#1._Identify_your_requirements"
      type: "int"
      default: 3
      required: true
    - variable: splunk_secret
      label: "Splunk Secret (pass4SymmKey)"
      description: "This is the key that authenticates communication between the all the nodes in the cluster. If this cluster is also being joined to an indexer cluster, this must be the same key as set on the master node."
      type: "password"
      required: true
    - variable: splunk_shc_nodes
      label: "Splunk Search Head Nodes"
      description: "Number of nodes in the cluster, excluding the captain which runs as a separate service. Should be a minimum of 2."
      type: "int"
      default: 2
      required: true
    - variable: splunk_master_node_service
      label: "Splunk Master Node"
      description: "Optional. Choose a service which is an indexer cluster master node to connect the SH cluster to an indexer cluster."
      type: "service"

services:
  shc-deployer:
    scale: 1
    start_on_create: true
  shc-node:
    scale: ${splunk_shc_nodes}
    start_on_create: true
  shc-captain:
    scale: 1
    start_on_create: true
  splunk-shc:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        selector: splunk=shc-node
        source_port: ${splunk_web_port}
        target_port: 8000
      stickiness_policy:
        cookie: sticky
        domain: ''
        indirect: false
        mode: insert
        nocache: false
        postonly: false
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
