version: '2'
services:
  test:
    image: busybox
    stdin_open: true
    tty: true
    command:
    - echo
    - ${splunk_master_node}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
